# Generated by Django 5.1.1 on 2024-11-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('job_position_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fk_department', models.ForeignKey(db_column='fk_department', on_delete=django.db.models.deletion.CASCADE, to='RRHH.department')),
            ],
            options={
                'db_table': 'job_position',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_VACATION', 'On Vacation'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('fk_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.jobposition')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee')),
            ],
            options={
                'db_table': 'salary_history',
            },
        ),
        migrations.CreateModel(
            name='PaymentDate',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('ADVANCE', 'Advance'), ('ON_TIME', 'On Time'), ('DELAYED', 'Delayed')], default='ON_TIME', max_length=20)),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee')),
                ('fk_salary_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.salaryhistory')),
            ],
            options={
                'db_table': 'payment_date',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='fk_salary_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RRHH.salaryhistory'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('pk_int', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('management_status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee')),
            ],
            options={
                'db_table': 'vacation',
            },
        ),
    ]
