# Generated by Django 5.1.1 on 2024-12-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
